#!/bin/sh

MITAMAE_OPT="--log-level=debug"

bin/setup install

case "$(uname)" in
  "Darwin")  ./bin/mitamae local $@ ./lib/bootstrap.rb --node-yaml=node.yaml --node-yaml=secret.yaml "$MITAMAE_OPT" ;;
  *) exit 1 ;;
esac

